model_name: "llama2-7b-4bits-no-invariant-length=800"
model_path: "/data/shared/llama2/llama-2-7b-chat-weights/"
max_length: 800
model_config:
  load_in_4bit: True
tokenizer_config:
  add_eos_token: true
  padding_side: 'left'
kwargs:
  nb_modules: 2 # Must be equal to "num_embeddings" in router config
  invariant_weight: 0.0
  hidden_dropout_prob: 0.1
  aggregation_strategy : "norm_hidden_states"

  