model_name: "llama2-7b-8bits"
model_path: "/data/shared/llama2/llama-2-7b-chat-weights/"
max_length: 512
model_config:
  load_in_8bit: True
  device_map: "auto"
tokenizer_config:
  add_eos_token: true
kwargs:
  nb_modules: 4
  invariant_weight: 1.0
  hidden_dropout_prob: 0.1

  