model_name: "timyllama-1.1b"
model_path: "TinyLlama/TinyLlama-1.1B-step-50K-105b"
max_length: 512
model_config: {}
tokenizer_config:
  add_eos_token: true
kwargs:
  nb_modules: 6 # Must be equal to "num_embeddings" in router config
  invariant_weight: 0.3
  hidden_dropout_prob: 0.1
  mi_dim_reduction: 256
  mi_dim_reduce_method: "max"

  