model_name: "timyllama-1.1b-4bits"
model_path: "TinyLlama/TinyLlama-1.1B-step-50K-105b"
max_length: 512
model_config:
  load_in_4bit: True
tokenizer_config:
  add_eos_token: true
  padding_side: 'left'
kwargs:
  nb_modules: 6 # Must be equal to "num_embeddings" in router config
  hidden_dropout_prob: 0.1
  mi_dim_reduction : 512
  mi_dim_reduce_method : "absmax"
  aggregation_strategy : "norm_hidden_states"
  hidden_size: 2048

  