model_name: "timyllama-1.1b-4bits-no-invariant"
model_path: "TinyLlama/TinyLlama-1.1B-step-50K-105b"
max_length: 512
model_config:
  load_in_4bit: True
tokenizer_config:
  add_eos_token: true
  padding_side: 'left'
kwargs:
  nb_modules: 6 # Must be equal to "num_embeddings" in router config
  invariant_weight: 0.0
  hidden_dropout_prob: 0.1

  