router_name: "input-reduced-gumbel-quantizer"
router_path: "InputReductionQuantizer"
routing_strategy:
  num_embeddings: 2 # Must be equal to "nb_modules" in model config
  embedding_dim: 4096
  quantize_fn: "gumbel"
  reduction_dim: 64
