router_name: "input-kmeans-cluster"
router_path: "InputLevelCluster"
pretrain_cluster: true
pretrain_batch_size: 4
routing_strategy:
  clustering_algorithm: "K-Means"
  num_embeddings: 2 # Must be equal to "nb_modules" in model config
  training_latents: null
