router_name: "input-vector-quantizer"
router_path: "InputQuantizer"
routing_strategy:
  num_embeddings: 4 # Must be equal to "nb_modules" in model config
  embedding_dim: 4096
  quantize_fn: "vector"
