model_name: "modular-llama2-7b-4bits-acre"
model_path: "fine-tuning-saves/fine-tuned-llama2-7b-4bits-input-reduced-vector-quantizer-TRAIN_ACRE_TASKS-2024-XX-XX_XX-XX-XX/"
max_length: 512
model_config: {}
tokenizer_config:
  add_eos_token: false
  padding_side: 'left'

  